apiVersion: v1
kind: Secret
metadata:
  name: finopsbank-secret
  namespace: finopsbank
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "Enginer012%"
  JWT_SECRET: "9f8a3b7c1e5d2f4a6b8c0e2d4f6a8b1c3d5e7f9a2b4c6d8e0f1a3b5c7d9e1f2a"