apiVersion: v1
kind: Secret
metadata:
  name: finopsbank-secret
  namespace: finopsbank
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  JWT_SECRET: "REPLACE_WITH_STRONG_64_CHAR_HEX_SECRET"