apiVersion: v1
kind: Namespace
metadata:
  name: finopsbank
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finopsbank-config
  namespace: finopsbank
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.containers.internal:5432/finopsbank"
---
apiVersion: v1
kind: Secret
metadata:
  name: finopsbank-secret
  namespace: finopsbank
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: RW5naW5lcjAxMiU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finopsbank-api
  namespace: finopsbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finopsbank-api
  template:
    metadata:
      labels:
        app: finopsbank-api
    spec:
      hostAliases:
      - ip: "10.0.2.2"
        hostnames:
        - "host.containers.internal"
      containers:
      - name: finopsbank-api
        image: finopsbank-api:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: finopsbank-config
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: finopsbank-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finopsbank-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: finopsbank-api-service
  namespace: finopsbank
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: finopsbank-api